const cars = [
    {
        name: 'Hyundai HB20',
        img: './image/groupCar/hatch/HB2X.png',
        price: 200,
        year: 2023,
        features: 'Direção Elétrica, Ar-Condicionado, Bluetooth',
        description: 'Compacto e prático, o hatch é perfeito para o dia a dia, combinando agilidade e economia.',
        description2: 'O Hyundai HB20 proporciona uma excelente experiência de viagem, ideal para quem deseja explorar novos destinos com segurança e conforto.',
        colors: ['black', 'silver', 'red'],
        category: 'hatch',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' },
        ]
    },
    {
        name: 'Chevrolet Onix',
        img: './image/groupCar/hatch/ONIC.png',
        price: 250,
        year: 2023,
        features: 'Direção Elétrica, Ar-Condicionado, Bluetooth',
        description: 'Um dos líderes de vendas, o Onix oferece conforto e tecnologia de ponta.',
        description2: 'O Chevrolet Onix é ideal para quem viaja em grupo, proporcionando espaço e conforto, além de ser perfeito para aventuras em família com o sistema de fidelidade.',
        colors: ['black', '#545452', 'white'],
        category: 'hatch',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🧳', feature: '1 mala grande' },
        ]
    },
    {
        name: 'Fiat Argo',
        img: './image/groupCar/hatch/ARGO.png',
        price: 200,
        year: 2023,
        features: 'Direção Elétrica, Ar-Condicionado, Bluetooth',
        description: 'Compacto e prático, o hatch é perfeito para o dia a dia, combinando agilidade e economia.',
        description2: 'O Fiat Argo oferece uma experiência de condução divertida e ágil, perfeito para quem busca praticidade e conforto durante suas viagens.',
        colors: ['black', 'silver', 'red'],
        category: 'hatch',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' },
        ]
    },
    {
        name: 'Hyundai HB20',
        img: './image/groupCar/hatch/HB2X.png',
        price: 200,
        year: 2023,
        features: 'Direção Elétrica, Ar-Condicionado, Bluetooth',
        description: 'Compacto e prático, o hatch é perfeito para o dia a dia, combinando agilidade e economia.',
        description2: 'O Hyundai HB20 proporciona uma excelente experiência de viagem, ideal para quem deseja explorar novos destinos com segurança e conforto.',
        colors: ['black', 'silver', 'red'],
        category: 'hatch',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' },
        ]
    },
    {
        name: 'Hyundai HB20',
        img: './image/groupCar/hatch/HB2X.png',
        price: 200,
        year: 2023,
        features: 'Direção Elétrica, Ar-Condicionado, Bluetooth',
        description: 'Compacto e prático, o hatch é perfeito para o dia a dia, combinando agilidade e economia.',
        description2: 'O Hyundai HB20 proporciona uma excelente experiência de viagem, ideal para quem deseja explorar novos destinos com segurança e conforto.',
        colors: ['black', 'silver', 'red'],
        category: 'hatch',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' },
        ]
    },
    {
        name: 'Hyundai HB20',
        img: './image/groupCar/hatch/HB2X.png',
        price: 200,
        year: 2023,
        features: 'Direção Elétrica, Ar-Condicionado, Bluetooth',
        description: 'Compacto e prático, o hatch é perfeito para o dia a dia, combinando agilidade e economia.',
        description2: 'O Hyundai HB20 proporciona uma excelente experiência de viagem, ideal para quem deseja explorar novos destinos com segurança e conforto.',
        colors: ['black', 'silver', 'red'],
        category: 'hatch',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' },
        ]
    },
];

export default cars;
