const cars = [
    //========================================================================================//
    //                                 CATEGORIA: HATCH                                       //
    //========================================================================================//
    {
        name: 'Hyundai HB20',
        img: '/image/groupCar/hatch/HB2X.png',
        price: 200,
        year: 2023,
        description: 'Compacto e prático, o hatch é perfeito para o dia a dia, combinando agilidade e economia.',
        description2: 'O Hyundai HB20 oferece economia e praticidade para enfrentar o trânsito urbano com conforto e estilo.',
        colors: ['black', 'silver', 'red'],
        category: 'hatch',
        features: 'Direção Elétrica, Ar-Condicionado, Bluetooth',
        features2: [
            { icon: '🔋', feature: 'Direção elétrica' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '📱', feature: 'Bluetooth' },
            { icon: '🚗', feature: '5 lugares' },
            { icon: '💺', feature: 'Banco de tecido' },
            { icon: '🎶', feature: 'Sistema de som' },
        ],
    },
    {
        name: 'Chevrolet Onix',
        img: '/image/groupCar/hatch/ONIC.png',
        price: 250,
        year: 2023,
        description: 'Um dos líderes de vendas, o Onix oferece conforto e tecnologia de ponta.',
        description2: 'O Chevrolet Onix traz inovação e conforto, oferecendo uma experiência de direção única e segura.',
        colors: ['black', '#545452', 'white'],
        category: 'hatch',
        features: 'Câmbio Automático, Sensor de Estacionamento, Tela Multimídia',
        features2: [
            { icon: '🔄', feature: 'Câmbio automático' },
            { icon: '🛑', feature: 'Sensor de estacionamento' },
            { icon: '📺', feature: 'Tela multimídia' },
            { icon: '🔊', feature: 'Sistema de som premium' },
            { icon: '🛠', feature: 'Manutenção preventiva' },
            { icon: '🧰', feature: 'Porta-malas espaçoso' },
        ],
    },
    {
        name: 'Fiat Argo',
        img: '/image/groupCar/hatch/ARGO.png',
        price: 220,
        year: 2023,
        description: 'O Fiat Argo oferece uma experiência de condução divertida e ágil e perfeito para quem busca praticidade.',
        description2: 'O Fiat Argo é perfeito para quem precisa de um carro compacto, econômico e confortável, ideal para o dia a dia e viagens rápidas.',
        colors: ['black', 'white', 'red'],
        category: 'hatch',
        features: 'Ar-condicionado, Vidro elétrico, Trava elétrica',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' },
        ],
    },
    {
        name: 'Volkswagen Gol',
        img: '/image/groupCar/hatch/GOLC.png',
        price: 180,
        year: 2023,
        description: 'O Volkswagen Gol é um carro versátil que se adapta facilmente a diferentes estilos de viagem, carro ágil e econômico.',
        description2: 'Com o Volkswagen Gol, você tem um carro ágil e econômico, ideal para o uso urbano e viagens mais curtas, com conforto e segurança.',
        colors: ['black', 'blue', 'white'],
        category: 'hatch',
        features: 'Ar-condicionado, Vidro elétrico, Direção hidráulica, Trava Elétrica',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🧳', feature: '2 malas pequenas' },
        ],
    },
    {
        name: 'Renault Kwid',
        img: '/image/groupCar/hatch/KWID.png',
        price: 150,
        year: 2023,
        description: 'O Renault Kwid é uma ótima opção para quem busca um carro compacto, ágil e econômico.',
        description2: 'Compacto e econômico, o Renault Kwid oferece agilidade no trânsito e um design moderno, perfeito para quem busca um carro prático e acessível.',
        colors: ['yellow', 'white', 'black'],
        category: 'hatch',
        features: 'Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🧳', feature: '1 mala pequena' },
        ],
    },
    {
        name: 'Volkswagen Polo',
        img: '/image/groupCar/hatch/POLO.png',
        price: 300,
        year: 2023,
        description: 'O Volkswagen Polo combina estilo moderno com tecnologia de ponta, oferecendo um desempenho superior.',
        description2: 'Perfeito para quem procura um carro ágil e sofisticado, o Polo proporciona uma experiência de direção emocionante com design arrojado e recursos inovadores.',
        colors: ['red', 'black', 'white'],
        category: 'hatch',
        features: 'Assistente de estacionamento, Ar-condicionado digital, Conectividade Bluetooth',
        features2: [
            { icon: '🚗', feature: 'Assistente de estacionamento' },
            { icon: '🌟', feature: 'Ar-condicionado digital' },
            { icon: '📱', feature: 'Conectividade Bluetooth' },
            { icon: '🗺️', feature: 'Sistema de navegação integrado' },
            { icon: '🔊', feature: 'Som premium' },
            { icon: '📸', feature: 'Câmera de ré' },
        ],
    },
    //========================================================================================//
    //                                 CATEGORIA: PICK-UP                                     //
    //========================================================================================//
    {
        name: 'Chevrolet S10',
        img: './image/groupCar/pick-up/S10X.png',
        price: 370,
        year: 2023,
        description: 'Combinando potência e conforto, a S10 é ideal para o trabalho e o lazer, proporcio uma experiência robusta e segura.',
        description2: 'A Chevrolet S10 é projetada para enfrentar qualquer estrada, proporcionando uma experiência robusta e segura para viagens de trabalho e lazer.',
        colors: ['black', 'silver', 'red'],
        category: 'pick-up',
        features: 'Ar-Condicionado, Câmbio Automático, Sistema de Navegação',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔄', feature: 'Câmbio automático' },
            { icon: '📍', feature: 'Sistema de navegação' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' },
        ],
    },
    {
        name: 'Fiat Toro',
        img: './image/groupCar/pick-up/TO4D.png',
        price: 330,
        year: 2023,
        description: 'A Toro oferece um design moderno e funcionalidades inovadoras para o dia a dia contrando com conforto em qualquer situação',
        description2: 'A Fiat Toro é a escolha ideal para quem busca versatilidade e estilo, combinando praticidade e conforto em qualquer situação.',
        colors: ['black', 'white', '#433634'],
        category: 'pick-up',
        features: 'Central Multimídia, Câmera de Ré, Controle de Trilha, Manutenção Inteligente',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '🎥', feature: 'Câmera de Ré' },
            { icon: '🔊', feature: 'Central Multimídia' },
            { icon: '🛣️', feature: 'Controle de Trilha' },
            { icon: '🔧', feature: 'Manutenção Inteligente' },
            { icon: '🚦', feature: 'ABS' },
        ],
    },
    {
        name: 'Nissan Frontier',
        img: '/image/groupCar/pick-up/FRON.png',
        price: 350,
        year: 2023,
        description: 'A Nissan Frontier é ideal para quem busca robustez e conforto, perfeita para aventuras fora de estrada.',
        description2: 'Com grande capacidade de carga e tecnologias inovadoras, a Nissan Frontier é a escolha perfeita para quem deseja explorar novos territórios com confiança.',
        colors: ['gray', 'black', 'white'],
        category: 'pick-up',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Trava elétrica, Air bag duplo, Suspensão elevada',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🛠', feature: 'Suspensão elevada' }
        ]
    },
    {
        name: 'Mitsubishi L200',
        img: '/image/groupCar/pick-up/L200.png',
        price: 330,
        year: 2023,
        description: 'A Mitsubishi L200 é uma picape que oferece força e resistência, ideal para quem deseja explorar terrenos desafiadores com segurança e confiança durante suas jornadas.',
        description2: 'Com um design robusto e tecnologias avançadas, a L200 é a escolha perfeita para quem não tem medo de desafios e busca potência sem abrir mão do conforto.',
        colors: ['silver', 'red', 'blue'],
        category: 'pick-up',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, 5 malas grandes',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🧳', feature: '5 malas grandes' }
        ]
    },
    {
        name: 'Chevrolet Montana',
        img: '/image/groupCar/pick-up/MONP.png',
        price: 290,
        year: 2023,
        description: 'A Chevrolet Montana é perfeita para quem procura uma picape compacta e versátil, ideal para aluguel em ambientes urbanos e rurais, garantindo agilidade e praticidade.',
        description2: 'Com sua facilidade de manobra e alto desempenho em diversos tipos de terreno, a Chevrolet Montana é a opção ideal para quem busca eficiência e conforto no dia a dia.',
        colors: ['red', 'black', 'silver'],
        category: 'pick-up',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Trava elétrica, Air bag duplo, Sistema de tração 4x4',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🧳', feature: 'Sistema de tração 4x4' }
        ]
    },
    {
        name: 'Toyota Hilux',
        img: '/image/groupCar/pick-up/TOYH.png',
        price: 450,
        year: 2023,
        description: 'A Toyota Hilux é sinônimo de durabilidade e confiabilidade, perfeita para quem busca uma picape de alto desempenho em qualquer condição, ideal para viagens longas e aventuras.',
        description2: 'Com um desempenho excepcional e um design robusto, a Toyota Hilux é ideal para quem enfrenta terrenos desafiadores sem abrir mão do conforto e segurança.',
        colors: ['white', 'silver', 'blue'],
        category: 'pick-up',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, Transmissão automática',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '⚙', feature: 'Transmissão automática' }
        ]
    },
    //========================================================================================//
    //                                 CATEGORIA: PREMIUM                                     //
    //========================================================================================//
    {
        name: 'Toyota Corolla',
        img: './image/groupCar/premium/COLB.png',
        price: 400,
        year: 2023,
        description: 'Um dos sedans mais vendidos, combina conforto, tecnologia em um só carro e proporcionando sempre uma condução eficiente, confortável e inovação',
        description2: 'O Toyota Corolla oferece sofisticação e inovação, proporcionando uma condução eficiente e confortável.',
        colors: ['black', 'silver', 'white'],
        category: 'premium',
        features: 'Assistência de Estacionamento, Conectividade, Ar-Condicionado Dual Zone',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '🔋', feature: 'Assistência de Estacionamento' },
            { icon: '📡', feature: 'Conectividade' },
            { icon: '❄️', feature: 'Ar-Condicionado Dual Zone' },
            { icon: '🛡', feature: 'Air Bag Frontal' },
            { icon: '🚦', feature: 'ABS' },
        ],
    },
    {
        name: 'Audi A3',
        img: './image/groupCar/premium/AUD3.png',
        price: 500,
        year: 2023,
        description: 'Um hatch premium que oferece performance e tecnologia avançada com detalhes que proporcionam uma experiência única.',
        description2: 'O Audi A3 é o carro ideal para quem busca luxo e performance, com detalhes que proporcionam uma experiência única.',
        colors: ['black', 'silver', 'blue'],
        category: 'premium',
        features: 'Sistema de Som Bang & Olufsen, Teto Solar Panorâmico, Sensor de Estacionamento',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '🔊', feature: 'Sistema de Som Bang & Olufsen' },
            { icon: '🌞', feature: 'Teto Solar Panorâmico' },
            { icon: '📍', feature: 'Sensor de Estacionamento' },
            { icon: '🛡', feature: 'Air Bag Frontal' },
            { icon: '🚦', feature: 'ABS' },
        ],
    },
    {
        name: 'Jeep Commander',
        img: '/image/groupCar/premium/CMDR.png',
        price: 500,
        year: 2023,
        description: 'O Jeep Commander é perfeito para aventuras familiares, conforto e uma capacidade off-road que o torna ideal para explorar novos destinos.',
        description2: 'Com tração 4x4 e desempenho robusto, o Jeep Commander proporciona uma experiência única tanto na cidade quanto fora de estrada.',
        colors: ['gray', 'white', 'black'],
        category: 'premium',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, Tração 4x4',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🌎', feature: 'Tração 4x4' }
        ]
    },
    {
        name: 'Chevrolet Equinox',
        img: '/image/groupCar/premium/EQBL.png',
        price: 450,
        year: 2023,
        description: 'O Chevrolet Equinox é ideal para famílias que buscam espaço e conforto, perfeito para viagens longas ou para o uso diário com muito estilo e funcionalidade.',
        description2: 'Com design moderno e funcionalidades inovadoras, o Chevrolet Equinox oferece segurança e desempenho, tornando-se o carro perfeito para qualquer ocasião.',
        colors: ['black', 'red', 'white'],
        category: 'premium',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, 5 malas pequenas',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🧳', feature: '5 malas pequenas' }
        ]
    }, {
        name: 'Haval H6',
        img: '/image/groupCar/premium/HAVA.png',
        price: 550,
        year: 2023,
        description: 'O Haval H6 traz inovação e tecnologia de ponta, oferecendo segurança e conforto para quem procura um SUV moderno para suas aventuras urbanas e rurais.',
        description2: 'Com recursos de segurança avançados e um design robusto, o Haval H6 é ideal para quem busca um SUV que se adapta a diferentes tipos de terreno e situações.',
        colors: ['blue', 'black', 'silver'],
        category: 'premium',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Trava elétrica, Air bag duplo, ABS',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' }
        ]
    },
    {
        name: 'Song Plus',
        img: '/image/groupCar/premium/SONG.png',
        price: 400,
        year: 2023,
        description: 'O Song Plus é uma opção inteligente e sustentável, ideal para quem valoriza eficiência energética e conforto, perfeito para quem quer alugar um carro ecológico e moderno.',
        description2: 'Com um motor elétrico potente e baixo impacto ambiental, o Song Plus oferece uma condução suave e eficiente para quem busca um estilo de vida mais verde.',
        colors: ['green', 'blue', 'white'],
        category: 'premium',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, Motor elétrico',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🔋', feature: 'Motor elétrico' }
        ]
    },
    //========================================================================================//
    //                                 CATEGORIA: SEDAN                                       //
    //========================================================================================//
    {
        name: 'Fiat Cronos',
        img: './image/groupCar/sedan/CROM.png',
        price: 270,
        year: 2023,
        description: 'O Fiat Cronos é a escolha ideal para quem busca um sedã com design moderno e desempenho eficiente, oferecendo conforto e tecnologia para uma experiência de direção suave e agradável em qualquer ocasião.',
        description2: 'Com tecnologia avançada e conforto, o Fiat Cronos é o sedan ideal para quem valoriza inovação e estilo.',
        colors: ['red', '#CBCBCC', 'black'],
        category: 'sedan',
        features: 'Tela Multimídia, Sensor de Estacionamento, Direção Elétrica, Painel Digital',
        features2: [
            { icon: '📺', feature: 'Tela Multimídia' },
            { icon: '📍', feature: 'Sensor de Estacionamento' },
            { icon: '🔄', feature: 'Direção Elétrica' },
            { icon: '📊', feature: 'Painel Digital' },
            { icon: '🛡', feature: 'Airbag Frontal' },
            { icon: '🚦', feature: 'Freios ABS' },
        ],
    },
    {
        name: 'Virtus',
        img: './image/groupCar/sedan/VIRF.png',
        price: 350,
        year: 2023,
        description: 'O Volkswagen Virtus é perfeito para quem busca desempenho e sofisticação, oferecendo um excelente espaço interno e conforto para longas viagens, ideal para quem valoriza qualidade.',
        description2: 'O Virtus proporciona uma experiência de direção segura e confortável, com tecnologia de última geração.',
        colors: ['black', 'white', '#82847F'],
        category: 'sedan',
        features: 'Controle de Estabilidade, Assistente de Subida, Painel Digital, Freios ABS, Ar-condicionado, Airbag Lateral',
        features2: [
            { icon: '🔄', feature: 'Controle de Estabilidade' },
            { icon: '🛣️', feature: 'Assistente de Subida' },
            { icon: '📊', feature: 'Painel Digital' },
            { icon: '🌡️', feature: 'Ar-condicionado' },
            { icon: '🛡', feature: 'Airbag Lateral' },
            { icon: '🚦', feature: 'Freios ABS' },
        ],
    },
    {
        name: 'Hyundai HB20S',
        img: '/image/groupCar/sedan/HB2C.png',
        price: 250,
        year: 2023,
        description: 'O Hyundai HB20S é ideal para quem busca praticidade e conforto, perfeito para famílias que desejam um carro espaçoso e confortável para suas viagens.',
        description2: 'Com um design moderno e acabamento sofisticado, o Hyundai HB20S é a escolha ideal para quem valoriza conforto e estilo no dia a dia.',
        colors: ['blue', 'black', 'white'],
        category: 'sedan',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, Espaço interno generoso',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '〽', feature: 'Espaço interno generoso' }
        ]
    },
    {
        name: 'Chevrolet Onix',
        img: '/image/groupCar/sedan/ONIS.png',
        price: 280,
        year: 2023,
        description: 'O Chevrolet Onix é perfeito para quem busca um carro compacto, econômico e cheio de estilo, ideal para o dia a dia, oferecendo conforto, tecnologia e um desempenho eficiente nas ruas e estradas.',
        description2: 'Com excelente economia de combustível e design inovador, o Chevrolet Onix oferece uma experiência de condução conectada e confortável.',
        colors: ['red', 'silver', 'black'],
        category: 'sedan',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Trava elétrica, Air bag duplo, 3 malas grandes',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🧳', feature: '3 malas grandes' }
        ]
    },
    {
        name: 'Nissan Sentra',
        img: '/image/groupCar/sedan/SETA.png',
        price: 300,
        year: 2023,
        description: 'O Nissan Sentra é a escolha perfeita para quem precisa de um carro prático e espaçoso, ideal para viagens longas com família e amigos, garantindo conforto em cada trajeto.',
        description2: 'Com design sofisticado e excelente desempenho, o Nissan Sentra proporciona uma experiência de condução tranquila e confortável.',
        colors: ['gray', 'blue', 'black'],
        category: 'sedan',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, Amplo porta-malas',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🧳', feature: 'Amplo porta-malas' }
        ]
    },
    //========================================================================================//
    //                                 CATEGORIA: SUV                                         //
    //========================================================================================//
    {
        name: 'Hyundai Creta',
        img: './image/groupCar/suv/CRTA.png',
        price: 450,
        year: 2023,
        features: 'Central Multimídia com Tela de 10", Câmera 360°, Assistência de Estacionamento',
        description: 'O Creta é um SUV que combina conforto e tecnologia em um só carro, sempre oferecendo conforto e segurança para toda a família.',
        description2: 'Com design moderno e avançado, o Hyundai Creta oferece conforto e segurança para toda a família.',
        colors: ['black', 'red', 'gray'],
        category: 'suv',
        features2: [
            { icon: '📺', feature: 'Central Multimídia com Tela de 10"' },
            { icon: '📸', feature: 'Câmera 360°' },
            { icon: '📍', feature: 'Assistência de Estacionamento' },
            { icon: '🌡️', feature: 'Ar-condicionado Digital' },
            { icon: '🛡', feature: 'Airbag Completo' },
            { icon: '🚦', feature: 'Freios ABS' },
        ],
    },
    {
        name: 'Fiat Fastback',
        img: '/image/groupCar/suv/FATB.png',
        price: 400,
        year: 2023,
        description: 'O Fiat Fastback é ideal para quem procura um carro com um visual dinâmico e sofisticado e com estilo para os amantes de condução ágil.',
        description2: 'Com design moderno e esportivo, o Fiat Fastback é perfeito para quem busca um carro que combine estilo e performance no dia a dia.',
        colors: ['red', 'white', 'black'],
        category: 'suv',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🌟', feature: 'Design esportivo' }
        ]
    },
    {
        name: 'Nissan Kicks',
        img: '/image/groupCar/suv/KICK.png',
        price: 450,
        year: 2023,
        description: 'O Nissan Kicks combina design moderno e eficiência, tornando-se a escolha ideal para quem busca um SUV compacto e conectado, perfeito para o dia a dia.',
        description2: 'Com tecnologia de ponta e economia de combustível, o Nissan Kicks é a opção ideal para quem deseja um SUV que alia estilo e praticidade.',
        colors: ['silver', 'black', 'blue'],
        category: 'suv',
        features:  'Trava elétrica, Air bag duplo, ABS, Ar-condicionado, Design esportivo',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' }
        ]
    },
    {
        name: 'Fiat Pulse',
        img: '/image/groupCar/suv/PLSE.png',
        price: 450,
        year: 2023,
        description: 'O Fiat Pulse é perfeito para quem quer um carro moderno e divertido, combinando estilo e tecnologia para uma experiência de aluguel que se destaca nas ruas.',
        description2: 'Com tecnologia de ponta e economia de combustível, o Nissan Kicks é a opção ideal para quem deseja um SUV que alia estilo e praticidade.',
        colors: ['silver', 'black', 'blue'],
        category: 'suv',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Trava elétrica, Air bag duplo, 3 malas grandes, ABS',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🛡', feature: 'Air bag duplo' },
            { icon: '🚦', feature: 'ABS' }
        ]
    },
    {
        name: 'Volkswagen Nivus',
        img: '/image/groupCar/suv/NIVU.png',
        price: 500,
        year: 2022,
        description: 'O Volkswagen Nivus é ideal para quem busca um SUV versátil e cheio de recursos, oferecendo conforto e tecnologia para uma experiência de direção prática e divertida.',
        description2: 'Com design moderno e várias funcionalidades, o Nivus oferece uma experiência de direção confortável e cheia de recursos tecnológicos.',
        colors: ['white', 'gray', 'blue'],
        category: 'suv',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, Trava elétrica, ABS',
        features2: [
            { icon: '🚪', feature: '4 portas' },
            { icon: '❄', feature: 'Ar-condicionado' },
            { icon: '🔌', feature: 'Vidro elétrico' },
            { icon: '🔒', feature: 'Trava elétrica' },
            { icon: '🚗', feature: 'Direção hidráulica' },
            { icon: '🛡', feature: 'Air bag duplo' }
        ]
    },
    {
        name: 'Chevrolet Tracker',
        img: '/image/groupCar/suv/TRAT.png',
        price: 480,
        year: 2023,
        description: 'O Chevrolet Tracker oferece uma combinação de estilo e segurança, ideal para quem procura um SUV compacto e confiável para suas aventuras urbanas e viagens.',
        description2: 'Com tecnologias de ponta e conforto, o Chevrolet Tracker é a escolha ideal para quem deseja um SUV que une praticidade e segurança.',
        colors: ['red', 'black', 'silver'],
        category: 'suv',
        features: '4 portas, Ar-condicionado, Vidro elétrico, Direção hidráulica, Air bag duplo, 3 malas grandes',
        features2: [
          { icon: '🚪', feature: '4 portas' },
          { icon: '❄', feature: 'Ar-condicionado' },
          { icon: '🔌', feature: 'Vidro elétrico' },
          { icon: '🚗', feature: 'Direção hidráulica' },
          { icon: '🛡', feature: 'Air bag duplo' },
          { icon: '🧳', feature: '3 malas grandes' }
        ]
      },
];

export default cars;
